config/routes.rb
Ecommerce::Application.routes.draw do
	match "home/index" => "home#index", :as => :homepage
	match "home/collections" => "home#collections", :as => :collections
	match "home/flash-xml" => "home#flash_xml", :as => :flash_xml
	match "videos/index" => "videos#index", :as => :videos
	match "videos/:id" => "videos#show", :as => :video

	namespace :admin do
		match "user/disapprove/:id" => "users#disapprove", :conditions => {:method => :post}, :as => :disapprove
		match "user/approve/:id" => "users#approve", :conditions => {:method => :post}, :as => :approve
		resources :videos
	end

	root :to => "home#index"

end

app/controllers/admin/taxonomies_controller.rb
class Admin::TaxonomiesController < Admin::ResourceController
  respond_to :json, :only => [:get_children]

  def get_children
    @taxons = Taxon.find(params[:parent_id]).children

    respond_with(@taxons)
  end

  private

  def location_after_save
    if @taxonomy.created_at == @taxonomy.updated_at
      edit_admin_taxonomy_url(@taxonomy)
    else
      admin_taxonomies_url
    end
  end
end

app/views/admin/taxonomies/_form.html.erb
<%= hook :admin_inside_taxonomy_form do %>
  <%= f.field_container :name do %>
    <%= f.label :name, t("name") %> <span class="required">*</span><br />
    <%= error_message_on :taxonomy, :name, :class => 'fullwidth title'  %>
    <%= text_field :taxonomy, :name  %>
  <% end %>
<% end %>

app/views/admin/taxonomies/_js_head.html.erb
<% content_for :head do %>
  <%= javascript_tag "var taxonomy_id = #{@taxonomy.id};
    var loading = '#{escape_javascript t('loading')}';
    var new_taxon = '#{escape_javascript t('new_taxon')}';
    var server_error = '#{escape_javascript t('server_error')}';
    var taxonomy_tree_error = '#{escape_javascript t('taxonomy_tree_error')}';"
  %>
  <%= javascript_include_tag 'taxonomy' , 'jquery.cookie.js', 'jsTree/jquery.jstree.js' %>
<% end %>

app/views/admin/taxonomies/_list.html.erb
<table class="index" id='listing_taxonomies'>
  <tr>
    <th><%= t("name") %></th>
    <th></th>
  </tr>
<% for taxonomy in @taxonomies %>
  <tr id="<%= dom_id taxonomy %>">
	  <td>
	    <%= taxonomy.name %>
    </td>
    <td class="actions">
      <%= link_to_edit taxonomy.id, :class => 'edit' %>
      &nbsp;
      <%= link_to_delete taxonomy %>
    </td>
  </tr>
<% end %>
</table>

app/views/admin/taxonomies/_taxon.html.erb
<% if taxon.children.length != 0 %>
  <ul>
    <% taxon.children.each do |child| %>
      <li id="<%= child.id %>" rel="taxon">
        <a style="background-image: url(<%=child.icon.url%>)" href="#"><%= child.name %></a>
        <% if child.children.length > 0 %>
          <%= render :partial => "taxon", :locals => {:taxon => child} %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/admin/taxonomies/edit.erb
<%= render :partial => 'admin/shared/configuration_menu' %>

<%= render :partial => "js_head" %>

<h1><%= t("taxonomy_edit")%></h1>

<p id="ajax_error" class="errorExplanation" style="display:none;"></p>

<%= form_for(:taxon, :url => admin_taxonomy_url, :html => { :method => :put }) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
	  <div>
	    <label><%= t("tree")%></label><br />
      <div id="taxonomy_tree" class="tree"></div>
  	</div>
  	<p id="progress" style="display:none;">
      <img src="/images/spinner.gif?1234540747" alt="Spinner" style="vertical-align:bottom;"/> <%= t('updating') %>..
    </p>
    <p><br/><small><%= t("taxonomy_tree_instruction")%></small></p>

	<p class="form-buttons">
	  <%= button t("update") %> <%= t("or") %> <%= link_to t("cancel"), admin_taxonomies_path %>
  </p>
<% end %>


<% content_for :head do %>
  <script type="text/javascript">
    var initial = [
	   	{ "attr" :
	   	  { "id" : "<%= @taxonomy.root.id %>", "rel" : "root" },
			"data" : "<%= @taxonomy.root.name %>",
			"state" : "open",
			"children" : [
				<% @taxonomy.root.children.each_with_index do |taxon,i| %>
					{
						"attr" :
						{ "id" : "<%= taxon.id %>"},
						"data" : "<%= taxon.name %>"
						<% unless taxon.children.empty? %>
							,"state" : "closed"
						<% end %>
					}<%= "," if i < (@taxonomy.root.children.size - 1) %>
				<% end %>
			]
      	}
    ];

  </script>
<% end %>

app/views/admin/taxonomies/get_children.json.erb
[<% @taxons.each_with_index do |t,i| %>
	{ "attr" :
	  { "id" : "<%= t.id %>" },
		"data" : "<%= t.name %>"
		<% unless t.children.empty? %>
			,"state" : "closed"
		<% end %>
	}<%= "," if i < (@taxons.size - 1) %>
<% end %>]

app/views/admin/taxonomies/index.html.erb
<%= render :partial => 'admin/shared/configuration_menu' %>

<div class='toolbar'>
  <ul class='actions'>
    <li>
      <%= button_link_to t("new_taxonomy"), new_admin_taxonomy_url, :icon => 'add', :id => 'admin_new_taxonomy_link' %></p>
    </li>
  </ul>
  <br class='clear' />
</div>

<h1><%= t("taxonomies") %></h1>

<div id='list-taxonomies'>
	<%= render :partial => 'list' %>
</div>

app/views/admin/taxonomies/new.html.erb
<%= render :partial => 'admin/shared/configuration_menu' %>

<h1><%= t("new_taxonomy") %></h1>

<%= form_for(:taxon, :url => collection_url) do |f| %>

	<%= render :partial => "form", :locals => { :f => f } %>

	<p class="form-buttons">
	  <%= button t("create") %>
  </p>
<% end %>